export const KEYWORDS_MAP: Record<string, string[]> = {
  js: ["javascript"],
  ts: ["typescript"],
  frontend: ["html", "css", "javascript", "react"],
  react: ["hooks", "jsx"],
  github: ["pull request", "merging"],
  framework: ["react", "next", "angular"],
  ai: ["chatgpt", "openai", "prompt"],
  post: ["blog"],
  styles: ["css", "tailwind"],
  jim: ["jdmedlock"],
  andre: ["andresc1310"],
  sql: ["database"],
  group: ["team"],
};
